include: package:flutter_lints/flutter.yaml

exclude:
  - "**/*.g.dart"

analyzer:
  errors:
    todo: warning
    avoid_types_on_closure_parameters: ignore
    avoid_dynamic_calls: ignore
  exclude:
    - '**/*_generated.dart'
    - '**/*.g.dart'

linter:
  rules:
    avoid_dynamic_calls: true
    always_use_package_imports: true
    avoid_print: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    camel_case_extensions: true
    cascade_invocations: true
    combinators_ordering: true
    constant_identifier_names: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_leading_underscores_for_local_identifiers: true
    no_literal_bool_comparisons: true
    null_closures: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: false
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: true
    sort_pub_dependencies: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: false
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    secure_pubspec_urls: true
