name: weather_map
description: "Weather Map App by ProjectMark"
publish_to: "none"
version: 2.0.1+9

environment:
  sdk: ^3.7.2

dependencies:
  ## Community Packages
  # Customizable carousel slider
  carousel_slider: ^5.0.0
  # Logs and erros capture
  catcher_2: ^2.1.2
  # Device preview
  device_preview: ^1.2.0
  # Http client
  dio: ^5.8.0+1
  # Improve web platform URL routes
  dynamic_path_url_strategy: ^1.0.0
  # Multiple languages support
  easy_localization: ^3.0.7+1
  ## Firebase Packages
  firebase_core: ^3.13.0
  firebase_core_platform_interface: ^5.4.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_remote_config: ^5.4.3
  # Flutter SDK
  flutter:
    sdk: flutter
  # Native splash screen
  flutter_native_splash: ^2.4.6
  # SVG support
  flutter_svg: ^2.0.17
  # Code generation
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  # State management and dependency injection
  get: ^4.7.2
  # Routes and navigation
  go_router: ^14.8.1
  # Themed fonts
  google_fonts: ^6.2.1
  # Local cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  # Internationalization
  intl: ^0.20.2
  # Logging
  logger: ^2.5.0

dev_dependencies:
  # Code generation
  build_runner: ^2.4.15
  # Change app package name
  change_app_package_name: ^1.3.0
  # Dependencies constraints validator
  dependency_validator: ^4.1.1
  # Scripts and tasks runner
  derry: ^1.5.0
  # Environment variables
  flutter_flavorizr: ^2.3.0
  # Code generation
  # flutter_gen_runner: ^5.10.0
  # Native launcher icons
  flutter_launcher_icons: ^0.14.3
  # Code quality and linting
  flutter_lints: ^5.0.0
  # Flutter Test
  flutter_test:
    sdk: flutter
  # Tests and mocks
  mockito: ^5.4.5
  mocktail: ^1.0.4
  # Sort pubspec.yaml dependencies
  pubspec_dependency_sorter: ^1.0.5

dependency_overrides:
  # Code generation
  freezed_annotation: ^3.0.0
  # Internationalization
  intl: ^0.20.2
  # Fix for Hive package
  source_gen: ^2.0.0

flavorizr:
  app:
    android:
      flavorDimensions: "app"
  flavors:
    prod:
      app:
        name: "Weather Map"
      android:
        applicationId: "com.projectmark.weather_map"
        customConfig:
          versionCode: flutterVersionCode.toInteger()
          versionName: flutterVersionName
      ios: null
    staging:
      app:
        name: "Weather Map staging"
      android:
        applicationId: "com.projectmark.weather_map"
        customConfig:
          versionCode: flutterVersionCode.toInteger()
          versionName: flutterVersionName
      ios: null
    dev:
      app:
        name: "Weather Map dev"
      android:
        applicationId: "com.projectmark.weather_map"
        customConfig:
          versionCode: flutterVersionCode.toInteger()
          versionName: flutterVersionName
      ios: null
        
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/logos/
    - assets/translations/
    - assets/videos/

scripts: derry.yaml
